server:
  port: 8080
  servlet:
    context-path: /


# 数据库连接配置，一定要在冒号后面加一个空格，否则无效
spring:
  datasource:
    driver-class-name: 
    url:
    username: 
    password: 
#  thymeleaf:
#    prefix: classpath:/t emplates/    
    